---
- name: Criar usuário ansible em todas as VMs
  hosts: all
  become: true
  tasks:
    - name: Criar usuário ansible
      user:
        name: ansible
        shell: /bin/bash
        create_home: yes

    - name: Adicionar ansible ao grupo sudo
      user:
        name: ansible
        groups: sudo
        append: yes

    - name: Configurar sudo sem senha para ansible
      copy:
        dest: /etc/sudoers.d/ansible
        content: "ansible ALL=(ALL) NOPASSWD:ALL\n"
        owner: root
        group: root
        mode: '0440'

    - name: Criar diretório .ssh para ansible
      file:
        path: /home/ansible/.ssh
        state: directory
        owner: ansible
        group: ansible
        mode: '0700'

    - name: Copiar chave pública para ansible
      copy:
        dest: /home/ansible/.ssh/authorized_keys
        content: "{{ lookup('env', 'ANSIBLE_PUBLIC_KEY') }}"
        owner: ansible
        group: ansible
        mode: '0600'
