---
- name: Instalar chave SSH do Semaphore nos servidores
  hosts: all
  become: true
  tasks:
    - name: Garantir que diretório .ssh existe
      file:
        path: "/root/.ssh"
        state: directory
        mode: '0700'
        owner: root
        group: root

    - name: Copiar chave pública para authorized_keys
      copy:
        dest: "/root/.ssh/authorized_keys"
        content: "{{ lookup('env', 'ANSIBLE_PUBLIC_KEY') }}"
        mode: '0600'
        owner: root
        group: root
