---
- name: Instalar chave SSH do Semaphore nos servidores
  hosts: all
  become: true
  tasks:
    - name: Garantir que diretório .ssh existe
      file:
        path: /home/ansible/.ssh
        state: directory
        owner: ansible
        group: ansible
        mode: '0700'

    - name: Adicionar chave pública do Semaphore ao usuário ansible
      authorized_key:
        user: ansible
        state: present
        key: "{{ ANSIBLE_PUBLIC_KEY }}"
