---
- name: Instalar chave SSH manualmente
  hosts: all
  become: true
  tasks:
    - name: Garantir que diretório .ssh existe
      file:
        path: /home/ansible/.ssh
        state: directory
        owner: ansible
        group: ansible
        mode: '0700'

    - name: Adicionar chave pública diretamente
      ansible.posix.authorized_key:
        user: ansible
        state: present
        key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGXoqKTs2A8JoGpfPCJzUMZTfC3PamjjGebN90pI/BhJ ansible@semaphore"
