---
- name: Instalar chave SSH do Semaphore nos servidores
  hosts: all
  become: true
  tasks:
    - name: Garantir que diretório .ssh existe
      file:
        path: /home/ansible/.ssh
        state: directory
        owner: ansible
        group: ansible
        mode: '0700'

    - name: Copiar chave pública para authorized_keys
      copy:
        dest: /home/ansible/.ssh/authorized_keys
        content: "{{ lookup('file', '/root/.ssh/id_ed25519.pub') }}"
        owner: ansible
        group: ansible
        mode: '0600'
