---
- name: Instalar utilitários básicos
  hosts: all
  become: true
  tasks:
    - name: Atualizar pacotes
      apt:
        update_cache: yes
        upgrade: dist

    - name: Instalar pacotes úteis
      apt:
        name:
          - curl
          - wget
          - git
          - unzip
          - gnupg
          - ca-certificates
          - lsb-release
          - software-properties-common
          - net-tools
          - htop
          - vim
          - tmux
          - bash-completion
          - nmap
          - traceroute
          - zsh
          - python3
          - python3-pip
          - jq
        state: present
